language: scala

scala: 2.11.0

env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

after_script:
  - export COVERALLS_REPO_TOKEN=wNDkXDytLqD7jbgRsmnaWMgdEiY7szljz
  - sbt coveralls
